//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BaoHanhModel", "FK_SanPham_HangSP", "HangSP", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BaoHanh.HangSP), "SanPham", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BaoHanh.SanPham), true)]
[assembly: EdmRelationshipAttribute("BaoHanhModel", "FK_ThongTinBaoHanh_KhachHang", "KhachHang", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BaoHanh.KhachHang), "ThongTinBaoHanh", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BaoHanh.ThongTinBaoHanh), true)]
[assembly: EdmRelationshipAttribute("BaoHanhModel", "FK_ThongTinBaoHanh_SanPham", "SanPham", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BaoHanh.SanPham), "ThongTinBaoHanh", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BaoHanh.ThongTinBaoHanh), true)]
[assembly: EdmRelationshipAttribute("BaoHanhModel", "FK_XuLyDonHang_TaiKhoan", "TaiKhoan", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BaoHanh.TaiKhoan), "XuLyDonHang", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BaoHanh.XuLyDonHang), true)]
[assembly: EdmRelationshipAttribute("BaoHanhModel", "FK_XuLyDonHang_ThongTinBaoHanh", "ThongTinBaoHanh", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BaoHanh.ThongTinBaoHanh), "XuLyDonHang", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BaoHanh.XuLyDonHang), true)]

#endregion

namespace BaoHanh
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BaoHanhEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BaoHanhEntities object using the connection string found in the 'BaoHanhEntities' section of the application configuration file.
        /// </summary>
        public BaoHanhEntities() : base("name=BaoHanhEntities", "BaoHanhEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BaoHanhEntities object.
        /// </summary>
        public BaoHanhEntities(string connectionString) : base(connectionString, "BaoHanhEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BaoHanhEntities object.
        /// </summary>
        public BaoHanhEntities(EntityConnection connection) : base(connection, "BaoHanhEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HangSP> HangSPs
        {
            get
            {
                if ((_HangSPs == null))
                {
                    _HangSPs = base.CreateObjectSet<HangSP>("HangSPs");
                }
                return _HangSPs;
            }
        }
        private ObjectSet<HangSP> _HangSPs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<KhachHang> KhachHangs
        {
            get
            {
                if ((_KhachHangs == null))
                {
                    _KhachHangs = base.CreateObjectSet<KhachHang>("KhachHangs");
                }
                return _KhachHangs;
            }
        }
        private ObjectSet<KhachHang> _KhachHangs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SanPham> SanPhams
        {
            get
            {
                if ((_SanPhams == null))
                {
                    _SanPhams = base.CreateObjectSet<SanPham>("SanPhams");
                }
                return _SanPhams;
            }
        }
        private ObjectSet<SanPham> _SanPhams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TaiKhoan> TaiKhoans
        {
            get
            {
                if ((_TaiKhoans == null))
                {
                    _TaiKhoans = base.CreateObjectSet<TaiKhoan>("TaiKhoans");
                }
                return _TaiKhoans;
            }
        }
        private ObjectSet<TaiKhoan> _TaiKhoans;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ThongTinBaoHanh> ThongTinBaoHanhs
        {
            get
            {
                if ((_ThongTinBaoHanhs == null))
                {
                    _ThongTinBaoHanhs = base.CreateObjectSet<ThongTinBaoHanh>("ThongTinBaoHanhs");
                }
                return _ThongTinBaoHanhs;
            }
        }
        private ObjectSet<ThongTinBaoHanh> _ThongTinBaoHanhs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<XuLyDonHang> XuLyDonHangs
        {
            get
            {
                if ((_XuLyDonHangs == null))
                {
                    _XuLyDonHangs = base.CreateObjectSet<XuLyDonHang>("XuLyDonHangs");
                }
                return _XuLyDonHangs;
            }
        }
        private ObjectSet<XuLyDonHang> _XuLyDonHangs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HangSPs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHangSPs(HangSP hangSP)
        {
            base.AddObject("HangSPs", hangSP);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the KhachHangs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKhachHangs(KhachHang khachHang)
        {
            base.AddObject("KhachHangs", khachHang);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SanPhams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSanPhams(SanPham sanPham)
        {
            base.AddObject("SanPhams", sanPham);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TaiKhoans EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTaiKhoans(TaiKhoan taiKhoan)
        {
            base.AddObject("TaiKhoans", taiKhoan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ThongTinBaoHanhs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToThongTinBaoHanhs(ThongTinBaoHanh thongTinBaoHanh)
        {
            base.AddObject("ThongTinBaoHanhs", thongTinBaoHanh);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the XuLyDonHangs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToXuLyDonHangs(XuLyDonHang xuLyDonHang)
        {
            base.AddObject("XuLyDonHangs", xuLyDonHang);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BaoHanhModel", Name="HangSP")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HangSP : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HangSP object.
        /// </summary>
        /// <param name="mahangsp">Initial value of the mahangsp property.</param>
        public static HangSP CreateHangSP(global::System.String mahangsp)
        {
            HangSP hangSP = new HangSP();
            hangSP.mahangsp = mahangsp;
            return hangSP;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mahangsp
        {
            get
            {
                return _mahangsp;
            }
            set
            {
                if (_mahangsp != value)
                {
                    OnmahangspChanging(value);
                    ReportPropertyChanging("mahangsp");
                    _mahangsp = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("mahangsp");
                    OnmahangspChanged();
                }
            }
        }
        private global::System.String _mahangsp;
        partial void OnmahangspChanging(global::System.String value);
        partial void OnmahangspChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tenhangsp
        {
            get
            {
                return _tenhangsp;
            }
            set
            {
                OntenhangspChanging(value);
                ReportPropertyChanging("tenhangsp");
                _tenhangsp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tenhangsp");
                OntenhangspChanged();
            }
        }
        private global::System.String _tenhangsp;
        partial void OntenhangspChanging(global::System.String value);
        partial void OntenhangspChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String kythuat
        {
            get
            {
                return _kythuat;
            }
            set
            {
                OnkythuatChanging(value);
                ReportPropertyChanging("kythuat");
                _kythuat = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("kythuat");
                OnkythuatChanged();
            }
        }
        private global::System.String _kythuat;
        partial void OnkythuatChanging(global::System.String value);
        partial void OnkythuatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sdt
        {
            get
            {
                return _sdt;
            }
            set
            {
                OnsdtChanging(value);
                ReportPropertyChanging("sdt");
                _sdt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sdt");
                OnsdtChanged();
            }
        }
        private global::System.String _sdt;
        partial void OnsdtChanging(global::System.String value);
        partial void OnsdtChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BaoHanhModel", "FK_SanPham_HangSP", "SanPham")]
        public EntityCollection<SanPham> SanPhams
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SanPham>("BaoHanhModel.FK_SanPham_HangSP", "SanPham");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SanPham>("BaoHanhModel.FK_SanPham_HangSP", "SanPham", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BaoHanhModel", Name="KhachHang")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class KhachHang : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new KhachHang object.
        /// </summary>
        /// <param name="makh">Initial value of the makh property.</param>
        public static KhachHang CreateKhachHang(global::System.String makh)
        {
            KhachHang khachHang = new KhachHang();
            khachHang.makh = makh;
            return khachHang;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String makh
        {
            get
            {
                return _makh;
            }
            set
            {
                if (_makh != value)
                {
                    OnmakhChanging(value);
                    ReportPropertyChanging("makh");
                    _makh = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("makh");
                    OnmakhChanged();
                }
            }
        }
        private global::System.String _makh;
        partial void OnmakhChanging(global::System.String value);
        partial void OnmakhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tenkh
        {
            get
            {
                return _tenkh;
            }
            set
            {
                OntenkhChanging(value);
                ReportPropertyChanging("tenkh");
                _tenkh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tenkh");
                OntenkhChanged();
            }
        }
        private global::System.String _tenkh;
        partial void OntenkhChanging(global::System.String value);
        partial void OntenkhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sdt
        {
            get
            {
                return _sdt;
            }
            set
            {
                OnsdtChanging(value);
                ReportPropertyChanging("sdt");
                _sdt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sdt");
                OnsdtChanged();
            }
        }
        private global::System.String _sdt;
        partial void OnsdtChanging(global::System.String value);
        partial void OnsdtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String diachi
        {
            get
            {
                return _diachi;
            }
            set
            {
                OndiachiChanging(value);
                ReportPropertyChanging("diachi");
                _diachi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("diachi");
                OndiachiChanged();
            }
        }
        private global::System.String _diachi;
        partial void OndiachiChanging(global::System.String value);
        partial void OndiachiChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BaoHanhModel", "FK_ThongTinBaoHanh_KhachHang", "ThongTinBaoHanh")]
        public EntityCollection<ThongTinBaoHanh> ThongTinBaoHanhs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ThongTinBaoHanh>("BaoHanhModel.FK_ThongTinBaoHanh_KhachHang", "ThongTinBaoHanh");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ThongTinBaoHanh>("BaoHanhModel.FK_ThongTinBaoHanh_KhachHang", "ThongTinBaoHanh", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BaoHanhModel", Name="SanPham")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SanPham : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SanPham object.
        /// </summary>
        /// <param name="mahang">Initial value of the mahang property.</param>
        public static SanPham CreateSanPham(global::System.String mahang)
        {
            SanPham sanPham = new SanPham();
            sanPham.mahang = mahang;
            return sanPham;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mahang
        {
            get
            {
                return _mahang;
            }
            set
            {
                if (_mahang != value)
                {
                    OnmahangChanging(value);
                    ReportPropertyChanging("mahang");
                    _mahang = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("mahang");
                    OnmahangChanged();
                }
            }
        }
        private global::System.String _mahang;
        partial void OnmahangChanging(global::System.String value);
        partial void OnmahangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tenhang
        {
            get
            {
                return _tenhang;
            }
            set
            {
                OntenhangChanging(value);
                ReportPropertyChanging("tenhang");
                _tenhang = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tenhang");
                OntenhangChanged();
            }
        }
        private global::System.String _tenhang;
        partial void OntenhangChanging(global::System.String value);
        partial void OntenhangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String seri
        {
            get
            {
                return _seri;
            }
            set
            {
                OnseriChanging(value);
                ReportPropertyChanging("seri");
                _seri = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("seri");
                OnseriChanged();
            }
        }
        private global::System.String _seri;
        partial void OnseriChanging(global::System.String value);
        partial void OnseriChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mahangsp
        {
            get
            {
                return _mahangsp;
            }
            set
            {
                OnmahangspChanging(value);
                ReportPropertyChanging("mahangsp");
                _mahangsp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mahangsp");
                OnmahangspChanged();
            }
        }
        private global::System.String _mahangsp;
        partial void OnmahangspChanging(global::System.String value);
        partial void OnmahangspChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BaoHanhModel", "FK_SanPham_HangSP", "HangSP")]
        public HangSP HangSP
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HangSP>("BaoHanhModel.FK_SanPham_HangSP", "HangSP").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HangSP>("BaoHanhModel.FK_SanPham_HangSP", "HangSP").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<HangSP> HangSPReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HangSP>("BaoHanhModel.FK_SanPham_HangSP", "HangSP");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<HangSP>("BaoHanhModel.FK_SanPham_HangSP", "HangSP", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BaoHanhModel", "FK_ThongTinBaoHanh_SanPham", "ThongTinBaoHanh")]
        public EntityCollection<ThongTinBaoHanh> ThongTinBaoHanhs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ThongTinBaoHanh>("BaoHanhModel.FK_ThongTinBaoHanh_SanPham", "ThongTinBaoHanh");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ThongTinBaoHanh>("BaoHanhModel.FK_ThongTinBaoHanh_SanPham", "ThongTinBaoHanh", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BaoHanhModel", Name="TaiKhoan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TaiKhoan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TaiKhoan object.
        /// </summary>
        /// <param name="username">Initial value of the username property.</param>
        public static TaiKhoan CreateTaiKhoan(global::System.String username)
        {
            TaiKhoan taiKhoan = new TaiKhoan();
            taiKhoan.username = username;
            return taiKhoan;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                if (_username != value)
                {
                    OnusernameChanging(value);
                    ReportPropertyChanging("username");
                    _username = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("username");
                    OnusernameChanged();
                }
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String hoten
        {
            get
            {
                return _hoten;
            }
            set
            {
                OnhotenChanging(value);
                ReportPropertyChanging("hoten");
                _hoten = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("hoten");
                OnhotenChanged();
            }
        }
        private global::System.String _hoten;
        partial void OnhotenChanging(global::System.String value);
        partial void OnhotenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sdt
        {
            get
            {
                return _sdt;
            }
            set
            {
                OnsdtChanging(value);
                ReportPropertyChanging("sdt");
                _sdt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sdt");
                OnsdtChanged();
            }
        }
        private global::System.String _sdt;
        partial void OnsdtChanging(global::System.String value);
        partial void OnsdtChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BaoHanhModel", "FK_XuLyDonHang_TaiKhoan", "XuLyDonHang")]
        public EntityCollection<XuLyDonHang> XuLyDonHangs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<XuLyDonHang>("BaoHanhModel.FK_XuLyDonHang_TaiKhoan", "XuLyDonHang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<XuLyDonHang>("BaoHanhModel.FK_XuLyDonHang_TaiKhoan", "XuLyDonHang", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BaoHanhModel", Name="ThongTinBaoHanh")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ThongTinBaoHanh : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ThongTinBaoHanh object.
        /// </summary>
        /// <param name="madonhang">Initial value of the madonhang property.</param>
        public static ThongTinBaoHanh CreateThongTinBaoHanh(global::System.String madonhang)
        {
            ThongTinBaoHanh thongTinBaoHanh = new ThongTinBaoHanh();
            thongTinBaoHanh.madonhang = madonhang;
            return thongTinBaoHanh;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String madonhang
        {
            get
            {
                return _madonhang;
            }
            set
            {
                if (_madonhang != value)
                {
                    OnmadonhangChanging(value);
                    ReportPropertyChanging("madonhang");
                    _madonhang = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("madonhang");
                    OnmadonhangChanged();
                }
            }
        }
        private global::System.String _madonhang;
        partial void OnmadonhangChanging(global::System.String value);
        partial void OnmadonhangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ngaynhanhang
        {
            get
            {
                return _ngaynhanhang;
            }
            set
            {
                OnngaynhanhangChanging(value);
                ReportPropertyChanging("ngaynhanhang");
                _ngaynhanhang = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ngaynhanhang");
                OnngaynhanhangChanged();
            }
        }
        private Nullable<global::System.DateTime> _ngaynhanhang;
        partial void OnngaynhanhangChanging(Nullable<global::System.DateTime> value);
        partial void OnngaynhanhangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ngaytrahang
        {
            get
            {
                return _ngaytrahang;
            }
            set
            {
                OnngaytrahangChanging(value);
                ReportPropertyChanging("ngaytrahang");
                _ngaytrahang = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ngaytrahang");
                OnngaytrahangChanged();
            }
        }
        private Nullable<global::System.DateTime> _ngaytrahang;
        partial void OnngaytrahangChanging(Nullable<global::System.DateTime> value);
        partial void OnngaytrahangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String makh
        {
            get
            {
                return _makh;
            }
            set
            {
                OnmakhChanging(value);
                ReportPropertyChanging("makh");
                _makh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("makh");
                OnmakhChanged();
            }
        }
        private global::System.String _makh;
        partial void OnmakhChanging(global::System.String value);
        partial void OnmakhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nhanvienKD
        {
            get
            {
                return _nhanvienKD;
            }
            set
            {
                OnnhanvienKDChanging(value);
                ReportPropertyChanging("nhanvienKD");
                _nhanvienKD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nhanvienKD");
                OnnhanvienKDChanged();
            }
        }
        private global::System.String _nhanvienKD;
        partial void OnnhanvienKDChanging(global::System.String value);
        partial void OnnhanvienKDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mahang
        {
            get
            {
                return _mahang;
            }
            set
            {
                OnmahangChanging(value);
                ReportPropertyChanging("mahang");
                _mahang = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mahang");
                OnmahangChanged();
            }
        }
        private global::System.String _mahang;
        partial void OnmahangChanging(global::System.String value);
        partial void OnmahangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> slnhan
        {
            get
            {
                return _slnhan;
            }
            set
            {
                OnslnhanChanging(value);
                ReportPropertyChanging("slnhan");
                _slnhan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("slnhan");
                OnslnhanChanged();
            }
        }
        private Nullable<global::System.Int32> _slnhan;
        partial void OnslnhanChanging(Nullable<global::System.Int32> value);
        partial void OnslnhanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sltrakhach
        {
            get
            {
                return _sltrakhach;
            }
            set
            {
                OnsltrakhachChanging(value);
                ReportPropertyChanging("sltrakhach");
                _sltrakhach = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sltrakhach");
                OnsltrakhachChanged();
            }
        }
        private Nullable<global::System.Int32> _sltrakhach;
        partial void OnsltrakhachChanging(Nullable<global::System.Int32> value);
        partial void OnsltrakhachChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tinhtranghangnhan
        {
            get
            {
                return _tinhtranghangnhan;
            }
            set
            {
                OntinhtranghangnhanChanging(value);
                ReportPropertyChanging("tinhtranghangnhan");
                _tinhtranghangnhan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tinhtranghangnhan");
                OntinhtranghangnhanChanged();
            }
        }
        private global::System.String _tinhtranghangnhan;
        partial void OntinhtranghangnhanChanging(global::System.String value);
        partial void OntinhtranghangnhanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String trangthaibaohanh
        {
            get
            {
                return _trangthaibaohanh;
            }
            set
            {
                OntrangthaibaohanhChanging(value);
                ReportPropertyChanging("trangthaibaohanh");
                _trangthaibaohanh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("trangthaibaohanh");
                OntrangthaibaohanhChanged();
            }
        }
        private global::System.String _trangthaibaohanh;
        partial void OntrangthaibaohanhChanging(global::System.String value);
        partial void OntrangthaibaohanhChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BaoHanhModel", "FK_ThongTinBaoHanh_KhachHang", "KhachHang")]
        public KhachHang KhachHang
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KhachHang>("BaoHanhModel.FK_ThongTinBaoHanh_KhachHang", "KhachHang").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KhachHang>("BaoHanhModel.FK_ThongTinBaoHanh_KhachHang", "KhachHang").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<KhachHang> KhachHangReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KhachHang>("BaoHanhModel.FK_ThongTinBaoHanh_KhachHang", "KhachHang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<KhachHang>("BaoHanhModel.FK_ThongTinBaoHanh_KhachHang", "KhachHang", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BaoHanhModel", "FK_ThongTinBaoHanh_SanPham", "SanPham")]
        public SanPham SanPham
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SanPham>("BaoHanhModel.FK_ThongTinBaoHanh_SanPham", "SanPham").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SanPham>("BaoHanhModel.FK_ThongTinBaoHanh_SanPham", "SanPham").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SanPham> SanPhamReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SanPham>("BaoHanhModel.FK_ThongTinBaoHanh_SanPham", "SanPham");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SanPham>("BaoHanhModel.FK_ThongTinBaoHanh_SanPham", "SanPham", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BaoHanhModel", "FK_XuLyDonHang_ThongTinBaoHanh", "XuLyDonHang")]
        public XuLyDonHang XuLyDonHang
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<XuLyDonHang>("BaoHanhModel.FK_XuLyDonHang_ThongTinBaoHanh", "XuLyDonHang").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<XuLyDonHang>("BaoHanhModel.FK_XuLyDonHang_ThongTinBaoHanh", "XuLyDonHang").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<XuLyDonHang> XuLyDonHangReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<XuLyDonHang>("BaoHanhModel.FK_XuLyDonHang_ThongTinBaoHanh", "XuLyDonHang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<XuLyDonHang>("BaoHanhModel.FK_XuLyDonHang_ThongTinBaoHanh", "XuLyDonHang", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BaoHanhModel", Name="XuLyDonHang")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class XuLyDonHang : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new XuLyDonHang object.
        /// </summary>
        /// <param name="madonhang">Initial value of the madonhang property.</param>
        public static XuLyDonHang CreateXuLyDonHang(global::System.String madonhang)
        {
            XuLyDonHang xuLyDonHang = new XuLyDonHang();
            xuLyDonHang.madonhang = madonhang;
            return xuLyDonHang;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String madonhang
        {
            get
            {
                return _madonhang;
            }
            set
            {
                if (_madonhang != value)
                {
                    OnmadonhangChanging(value);
                    ReportPropertyChanging("madonhang");
                    _madonhang = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("madonhang");
                    OnmadonhangChanged();
                }
            }
        }
        private global::System.String _madonhang;
        partial void OnmadonhangChanging(global::System.String value);
        partial void OnmadonhangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ngayhethan
        {
            get
            {
                return _ngayhethan;
            }
            set
            {
                OnngayhethanChanging(value);
                ReportPropertyChanging("ngayhethan");
                _ngayhethan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ngayhethan");
                OnngayhethanChanged();
            }
        }
        private Nullable<global::System.DateTime> _ngayhethan;
        partial void OnngayhethanChanging(Nullable<global::System.DateTime> value);
        partial void OnngayhethanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ghichu1
        {
            get
            {
                return _ghichu1;
            }
            set
            {
                Onghichu1Changing(value);
                ReportPropertyChanging("ghichu1");
                _ghichu1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ghichu1");
                Onghichu1Changed();
            }
        }
        private global::System.String _ghichu1;
        partial void Onghichu1Changing(global::System.String value);
        partial void Onghichu1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ghichu2
        {
            get
            {
                return _ghichu2;
            }
            set
            {
                Onghichu2Changing(value);
                ReportPropertyChanging("ghichu2");
                _ghichu2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ghichu2");
                Onghichu2Changed();
            }
        }
        private global::System.String _ghichu2;
        partial void Onghichu2Changing(global::System.String value);
        partial void Onghichu2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ghichu3
        {
            get
            {
                return _Ghichu3;
            }
            set
            {
                OnGhichu3Changing(value);
                ReportPropertyChanging("Ghichu3");
                _Ghichu3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ghichu3");
                OnGhichu3Changed();
            }
        }
        private global::System.String _Ghichu3;
        partial void OnGhichu3Changing(global::System.String value);
        partial void OnGhichu3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ketqua
        {
            get
            {
                return _ketqua;
            }
            set
            {
                OnketquaChanging(value);
                ReportPropertyChanging("ketqua");
                _ketqua = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ketqua");
                OnketquaChanged();
            }
        }
        private global::System.String _ketqua;
        partial void OnketquaChanging(global::System.String value);
        partial void OnketquaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String trangthaixuly
        {
            get
            {
                return _trangthaixuly;
            }
            set
            {
                OntrangthaixulyChanging(value);
                ReportPropertyChanging("trangthaixuly");
                _trangthaixuly = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("trangthaixuly");
                OntrangthaixulyChanged();
            }
        }
        private global::System.String _trangthaixuly;
        partial void OntrangthaixulyChanging(global::System.String value);
        partial void OntrangthaixulyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BaoHanhModel", "FK_XuLyDonHang_TaiKhoan", "TaiKhoan")]
        public TaiKhoan TaiKhoan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TaiKhoan>("BaoHanhModel.FK_XuLyDonHang_TaiKhoan", "TaiKhoan").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TaiKhoan>("BaoHanhModel.FK_XuLyDonHang_TaiKhoan", "TaiKhoan").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TaiKhoan> TaiKhoanReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TaiKhoan>("BaoHanhModel.FK_XuLyDonHang_TaiKhoan", "TaiKhoan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TaiKhoan>("BaoHanhModel.FK_XuLyDonHang_TaiKhoan", "TaiKhoan", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BaoHanhModel", "FK_XuLyDonHang_ThongTinBaoHanh", "ThongTinBaoHanh")]
        public ThongTinBaoHanh ThongTinBaoHanh
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ThongTinBaoHanh>("BaoHanhModel.FK_XuLyDonHang_ThongTinBaoHanh", "ThongTinBaoHanh").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ThongTinBaoHanh>("BaoHanhModel.FK_XuLyDonHang_ThongTinBaoHanh", "ThongTinBaoHanh").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ThongTinBaoHanh> ThongTinBaoHanhReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ThongTinBaoHanh>("BaoHanhModel.FK_XuLyDonHang_ThongTinBaoHanh", "ThongTinBaoHanh");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ThongTinBaoHanh>("BaoHanhModel.FK_XuLyDonHang_ThongTinBaoHanh", "ThongTinBaoHanh", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
